
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  
jobs:
  DEV:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_'
          tokenSuffix: '_'
          files: '["**/*roshan.txt"]'
        env:
          hru: mygoditssuperb
          
      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/roshan.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/roshan.txt
          

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact
    
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: path/to/artifact/roshan.txt
          
          
    
 
